--Updates salary based on years of experience

CREATE OR REPLACE PROCEDURE
RAISESALARY AS
CURSOR cursor_EMPLOYEE IS
SELECT * FROM EMPLOYEE FOR UPDATE;
thisEMPLOYEE cursor_EMPLOYEE%ROWTYPE;
SCORE DECIMAL(2,1);
COUNT_DRIVER INTEGER;
BEGIN
  OPEN cursor_EMPLOYEE;
  LOOP
    FETCH cursor_EMPLOYEE INTO thisEMPLOYEE;
    EXIT WHEN (cursor_EMPLOYEE%NOTFOUND);
    SELECT COUNT(*) INTO COUNT_DRIVER FROM DRIVER WHERE SSN = thisEmployee.SSN AND AVERAGE_SCORE>=4.5;
    IF COUNT_DRIVER > 0 THEN
      UPDATE EMPLOYEE SET SALARY = SALARY * 1.07
      WHERE CURRENT OF cursor_EMPLOYEE; 
    ELSE 
      UPDATE EMPLOYEE SET SALARY = SALARY * 1.05
      WHERE CURRENT OF cursor_EMPLOYEE; 
    END IF;
  END LOOP;
CLOSE cursor_EMPLOYEE;
END;
.
RUN;

begin
RAISESALARY;
end;
