CREATE TABLE CUSTOMER
(Ssn DECIMAL(9,0) NOT NULL, 
Fname VARCHAR(15) NOT NULL,
Minit CHAR(1),
Lname VARCHAR(15) NOT NULL,
Phone CHAR(10),
Email VARCHAR(40),
City VARCHAR(20),
State VARCHAR(20),
Street VARCHAR(20),
CONSTRAINT CUST_PK PRIMARY KEY (Ssn));

CREATE TABLE EMPLOYEE
(Ssn DECIMAL(9,0) NOT NULL, 
Fname VARCHAR(15) NOT NULL,
Minit CHAR(1),
Lname VARCHAR(15) NOT NULL,
Phone CHAR(10),
Email VARCHAR(40),
Salary DECIMAL(10,2),
Start_Time VARCHAR(5),
End_Time VARCHAR(5),
Hire_Date DATE,
CONSTRAINT EMP_PK
PRIMARY KEY (Ssn));

CREATE TABLE CREDITCARD
(Ssn DECIMAL(9,0) NOT NULL, 
Card_Number INTEGER, 
CVV INTEGER, 
Expiration_Date DATE,
CONSTRAINT CC_FK FOREIGN KEY (Ssn) REFERENCES CUSTOMER(SSN) 
ON DELETE CASCADE,
CONSTRAINT CC_PK PRIMARY KEY(Card_Number));

CREATE TABLE DRIVER
(Ssn DECIMAL(9,0) NOT NULL,
Status CHAR(1) DEFAULT 'Y',
Average_Score DECIMAL(2,1),
NumOfReviews NUMBER DEFAULT 0,
CONSTRAINT DRIVER_EMP_FK 
FOREIGN KEY (Ssn) REFERENCES EMPLOYEE(Ssn) 
ON DELETE CASCADE,
CONSTRAINT DRIVER_PK 
PRIMARY KEY(Ssn));

CREATE TABLE DISPATCHER
(Ssn DECIMAL(9,0) NOT NULL,
CONSTRAINT DISP_EMP_FK FOREIGN KEY (Ssn) REFERENCES EMPLOYEE(Ssn) 
ON DELETE CASCADE,
CONSTRAINT DISP_PK PRIMARY KEY(Ssn));

CREATE TABLE WORKING_DAYS
( Ssn DECIMAL(9,0) NOT NULL,
Day CHAR(3) NOT NULL,
CONSTRAINT WD_PK
PRIMARY KEY (ssn, Day),
CONSTRAINT WD_EMP_FK
FOREIGN KEY (Ssn) REFERENCES EMPLOYEE(Ssn)
ON DELETE CASCADE);

CREATE TABLE RIDE_REQUEST
(Request_ID VARCHAR(10) NOT NULL, 
No_of_Passengers INTEGER, 
Wheel_Chair_Access char(1), 
Status VARCHAR(10), 
Pickup_Street Varchar(25), 
Pickup_City Varchar(25), 
Drop_Street Varchar(25), 
Drop_City Varchar(25), 
Request_Date DATE, 
Customer_SSN DECIMAL(9,0), 
CONSTRAINT RR_PK 
PRIMARY KEY(Request_ID),
CONSTRAINT RR_CUST_FK 
FOREIGN KEY(Customer_SSN) REFERENCES CUSTOMER(SSN) 
ON DELETE SET NULL);

CREATE TABLE TAXI_MODEL
(modelType VARCHAR(20) NOT NULL,
No_Of_Seats INTEGER NOT NULL,
Price_rate DECIMAL(4,2) DEFAULT 2.50,
CONSTRAINT TM_PK
PRIMARY KEY (modelType));

CREATE TABLE TAXI
(Vehicle_no VARCHAR(10) NOT NULL, 
modelType Varchar(20) NOT NULL, 
Purchase_Date DATE,
Status char(1) DEFAULT 'Y',
Wheel_Chair_Access char(1) DEFAULT 'N', 
CONSTRAINT T_PK 
PRIMARY KEY(Vehicle_no), 
CONSTRAINT T_TM_FK 
FOREIGN KEY(modelType) REFERENCES TAXI_MODEL(modelType));

CREATE TABLE RIDE(
Request_ID VARCHAR(10) NOT NULL,
Ssn DECIMAL(9,0),
Vehicle_no VARCHAR(10),
Start_date DATE NOT NULL,
End_date DATE,
Distance Decimal(6,3),
Ride_Cost Decimal(6,3),
CONSTRAINT RIDE_RR_FK 
FOREIGN KEY(Request_ID) REFERENCES RIDE_REQUEST(Request_ID) 
ON DELETE CASCADE,
CONSTRAINT RIDE_DRIVER_FK 
FOREIGN KEY(Ssn) REFERENCES DRIVER(Ssn) 
ON DELETE SET NULL,
CONSTRAINT RIDE_TAXI_FK 
FOREIGN KEY(Vehicle_no) REFERENCES TAXI(Vehicle_no) 
ON DELETE SET NULL,
CONSTRAINT RIDE_PK 
PRIMARY KEY(Request_ID));

CREATE TABLE CERTIFICATION(
DriverSSN DECIMAL(9,0) NOT NULL,
modelType VARCHAR(20) NOT NULL, 
CONSTRAINT CERT_DRIVER_FK 
FOREIGN KEY(DriverSSN) REFERENCES DRIVER(Ssn) 
ON DELETE CASCADE,
CONSTRAINT CERT_TM_FK 
FOREIGN KEY(modelType) REFERENCES TAXI_MODEL(modelType) 
ON DELETE CASCADE,
CONSTRAINT CERT_PK 
PRIMARY KEY(DriverSSN, modelType));

CREATE TABLE REVIEW
( Cust_Ssn DECIMAL(9,0) NOT NULL,
Driver_Ssn DECIMAL(9,0) NOT NULL,
Score INTEGER,
CONSTRAINT REVIEW_PK
PRIMARY KEY (Cust_Ssn, Driver_Ssn),
CONSTRAINT REVIEW_EMP_FK
FOREIGN KEY (Driver_Ssn) REFERENCES DRIVER(Ssn)
ON DELETE SET NULL,
CONSTRAINT REVIEW_CUST_FK
FOREIGN KEY (Cust_Ssn) REFERENCES CUSTOMER(Ssn)
ON DELETE SET NULL);